version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-browsers
    working_directory: ~/ock-pay
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run:
          name: Codecov
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
